# ------------------------------------------------
# Camerons Ansible PlayBook 6
#
# Purpose:  Test conditions in ansible only on windows 
# ------------------------------------------------
- name: Cam's playbook 6 (Name)
  gather_facts: yes
  hosts: all

  # Variables - lines to add to hosts file
  vars:
    lines:
    - 192.0.1.99 foo.cam.net
    - 192.0.1.100 foo.cam.net
    - 192.0.1.101 foo.cam.net
    - 192.0.1.102 foo.cam.net

  tasks:
  # Read windows contents of the hosts file into host_info 
  - name: Read contents of file
    win_shell: Get-Content -Path c:\Windows\System32\Drivers\etc\hosts
    register: hosts_info
    when: ansible_system == "Win32NT"

  # Loop through lines and add add if they do not exist
  - name: Add line to file if
    win_lineinfile:
      path: c:\Windows\System32\Drivers\etc\hosts
      line: "{{ item }}"
      insertafter: EOF
    when: ansible_system == "Win32NT" and not item in hosts_info.stdout
    loop: "{{ lines }}"
