# ------------------------------------------------
# Camerons check for a line of code update if not there 
# ------------------------------------------------
- name: Windows check for line and add if not there 
  gather_facts: false
  hosts: all
  vars:
      conf_dir: 'C:\Program Files\ILMT\config\'
      conf_file: 'computer_properties.yml'

  tasks:

    # Check if the ILMT folder exists
    - name: Look for ILMT config folder
      win_stat:
        path: '{{ conf_dir }}'
      register: folder_check 

    - name: Find the file
      win_find:
        paths: '{{ conf_dir }}' 
        patterns: '{{ conf_file }}'
      register: file_result      
      ignore_errors: true
      when: folder_check.stat.exists == true

    # Create a missing config file 
    - name: Create a missing configuration file
      win_copy:
        src:  'files/{{ conf_file }}'
        dest: '{{ conf_dir }}{{ conf_file }}'
      when: 
        - folder_check.stat.exists == true
        - file_result.matched == 0

    # changed out  path: "{{ file_result.files[0].path }}"
    - name: Check if string exists in file
      win_lineinfile:
        path: '{{ conf_dir }}{{ conf_file }}'
        regexp: '.*AnsibleOrg:*'
        LINE: 'AnsibleOrg: tpa'
        state: present
      register: string_check_result
      when: 
        - folder_check.stat.exists == true
        - file_result.matched > 0

    #- name: Print string existence status
    #  debug:
    #    msg: "String exists in file: {{ string_check_result }}"
    #  when: file_result.matched > 0
    