# ------------------------------------------------
# Camerons check for a line of code update if not there 
# ------------------------------------------------
- name: Windows check for line and add if not there 
  hosts: all

  tasks: