# ------------------------------------------------
# Camerons check for a line of code update if not there 
# ------------------------------------------------
- name: Windows check for line and add if not there 
  hosts: all

  tasks:
    #- name: Find the file
    #  win_find:
    #    paths: C:\Program Files\ILMT\config\ 
    #    patterns: 'computer_properties.yml'
    #  register: file_result      
    #  ignore_errors: true
    

    # changed out  path: "{{ file_result.files[0].path }}"
    - name: Check if string exists in file
      win_lineinfile:
        path:  C:\Program Files\ILMT\config\computer_properties2.yml
        regexp: '.*AnsibleOrg:*'
        LINE: 'AnsibleOrg: tpa'
        state: present
      register: string_check_result
    #  when: file_result.matched > 0

    #- name: Print string existence status
    #  debug:
    #    msg: "String exists in file: {{ string_check_result }}"
    #  when: file_result.matched > 0
    