# ------------------------------------------------
# Camerons check for a line of code update if not there 
# ------------------------------------------------
- name: Windows check for line and add if not there 
  gather_facts: false
  hosts: all
 
  tasks:

     # Get the log sizing data from  the server
    - name: Run windows config check
      include_tasks: "tasks/win_check.yml"
