# ------------------------------------------------
# Camerons check for a line of code update if not there 
# ------------------------------------------------
- name: Windows check for line and add if not there 
  gather_facts: false
  hosts: all
  vars:
    conf_dir: 'C:\Program Files\ILMT\config\'
    conf_file: 'computer_properties.yml'
 
  tasks:

     # Get the log sizing data from  the server
    - name: Run windows config check
      include_tasks: "tasks/win_check.yml"
