# ------------------------------------------------
# Camerons check for a line of code update if not there 
# ------------------------------------------------
- name: Windows check for line and add if not there 
  hosts: all

  tasks:

    # Check if the ILMT folder exists
    - name: Look for ILMT config folder
      win_stat:
        path: 'C:\Program Files\ILMT\config\'
      register: folder_check 

    - name: Find the file
      win_find:
        paths: C:\Program Files\ILMT\config\ 
        patterns: 'computer_properties.yml'
      register: file_result      
      ignore_errors: true
      when: folder_check.stat.exists == true

    # Create a missing config file 
    - name: Create a missing configuration file
      copy:
        content: 'AnsibleOrg: tpa'
        dest: 'C:\Program Files\ILMT\config\computer_properties.yml'
      when: 
        - folder_check.stat.exists == true
        - file_result.matched == 0

    # changed out  path: "{{ file_result.files[0].path }}"
    - name: Check if string exists in file
      win_lineinfile:
        path:  C:\Program Files\ILMT\config\computer_properties.yml
        regexp: '.*AnsibleOrg:*'
        LINE: 'AnsibleOrg: tpa'
        state: present
      register: string_check_result
      when: 
        - folder_check.stat.exists == true
        - file_result.matched > 0

    #- name: Print string existence status
    #  debug:
    #    msg: "String exists in file: {{ string_check_result }}"
    #  when: file_result.matched > 0
    